context:
  version: "0.0.3"

package:
  name: jupyter-ai-magic-commands
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/j/jupyter-ai-magic-commands/jupyter_ai_magic_commands-${{ version }}.tar.gz
  sha256: 39b2436eef41636aae5285f8360ac11228c99910a85f4a968030b64616e10d6b

build:
  noarch: python
  script: python -m pip install . -vv
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling >=1.4.0
  run:
    - python >=${{ python_min }}
    - click >=8.1.0,<9
    - ipython
    - pydantic >=2.10.0,<3

tests:
  - python:
      imports:
        - jupyter_ai_magic_commands
      pip_check: true
    requirements:
      run:
        - python ${{ python_min }}.*

about:
  homepage: https://github.com/jupyter-ai-contrib/jupyter-ai-magic-commands
  summary: "Magic commands for using LLMs in Jupyter notebooks"
  license: BSD-3-Clause
  license_file: LICENSE
  documentation: https://jupyter-ai.readthedocs.io/
  repository: https://github.com/jupyter-ai-contrib/jupyter-ai-magic-commands

extra:
  recipe-maintainers:
    - dlqqq
    - andrii-i
